### ISSUE TITLE
It covers the Audiotab icon plus's icon and also there's no hover feedback on the button

### ISSUE THREAD

**Issue by ProbablyM-S** [burnt0rice/zen-themes#1]
video showing the issue
https://github.com/user-attachments/assets/6e2b02e6-7619-4e63-bf20-db6df393286e

Great work btw! :)

**Comment by KiKaraage** [comment]
Personally I would suggest changes to AudioTab Icon Plus' author @DaityDay more than to this repo - so we can have options to put the audio indicator on the left side of tab icon. Audio icon on top left side and close button on the top right side would be much more ideal!

**Comment by burnt0rice** [comment]
Thank you for your feedback. I will add the missing hover effect.

I agree with @KiKaraage — theoretically, the close button should be on the top-right. Would it be a good compromise to add a preference to optionally move the close button to the top-left?

**Comment by ProbablyM-S** [comment]
> Personally I would suggest changes to AudioTab Icon Plus' author @DaityDay more than to this repo - so we can have options to put the audio indicator on the left side of tab icon. Audio icon on top left side and close button on the top right side would be much more ideal!

yeah true I did think about that after opening this issue I'll actually ask the Audio Tab Icon Plus dev for it.
it will definitely make more sense to have the close button on the right and I dont think adding a preference to move the close button to the left is really needed

> Thank you for your feedback. I will add the missing hover effect.
> 
> I agree with @KiKaraage — theoretically, the close button should be on the top-right. Would it be a good compromise to add a preference to optionally move the close button to the top-left?

I dont think the option is really needed I should just ask the Audio Tab Icon Plus dev for it
you should just add the hover effect sorry.

**Comment by benstone326** [comment]
On light mode there's no BG behind the X. I would suggest a white BG.
![image](https://github.com/user-attachments/assets/3e6d3bfb-0dc5-4079-ac2c-1a1aca69f672)

**Comment by cprin21** [comment]
Now it just doesn't work on a.35

**Comment by burnt0rice** [comment]
I've implemented the hover effect and will wait until I've resolved issue #5. After that, I'll request an update for this theme.

**Comment by burnt0rice** [comment]
The theme has been updated and is now available in the theme store.
