### ISSUE TITLE
Doesn't work on a.35

### ISSUE THREAD

**Issue by burnt0rice** [burnt0rice/zen-themes#6]
Now it just doesn't work on a.35

_Originally posted by @cprin21 in https://github.com/burnt0rice/zen-themes/issues/1#issuecomment-2329456155_

**Comment by burnt0rice** [comment]
Hi @cprin21, I downloaded version a.35, and on my end, the theme is still working. Could you please provide more information on how to reproduce the issue you're experiencing?

**Comment by cprin21** [comment]
After downgrading the browser to a.34 then updating again to a.35 the theme now works as expected on a.35, so this was in some way an issue on my install/update rather than an issue with this theme. Sorry!

**Comment by burnt0rice** [comment]
Great! I'm happy to see that the theme is working on your end.
